name: Déploiement VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Exécuter le déploiement sur le VPS
    - name: Debug secrets
      run: echo "Host is ${{ secrets.VPS_HOST }}"
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        fingerprint: ${{ secrets.KNOWN_HOSTS }}
        script: |
         cd /srv/monsiteweb
         git fetch --all
         git reset --hard origin/main
         source venv_django/bin/activate
         pip install -r requirements.txt
         python manage.py migrate --noinput
         python manage.py collectstatic --noinput
         sudo systemctl reload apache2
