name: Déploiement VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Exécuter le déploiement sur le VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          /srv/monsiteweb/deploy.sh
        # première exécution : ignorer la vérification du fingerprint
        args: "-o StrictHostKeyChecking=no"
