name: Déploiement VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Exécuter le déploiement sur le VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
            set -e
            # 1. Crée/écrase le .env avec les secrets GitHub
            cat <<EOF > /srv/monsiteweb/.env
            DEBUG=False
            DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
            ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            GMAIL_CLIENT_ID=${{ secrets.GMAIL_CLIENT_ID }}
            GMAIL_CLIENT_SECRET=${{ secrets.GMAIL_CLIENT_SECRET }}
            GMAIL_REFRESH_TOKEN=${{ secrets.GMAIL_REFRESH_TOKEN }}
            CONTACT_EMAIL=${{ secrets.CONTACT_EMAIL }}
            EOF
           
            # Fixe les permissions
            chown deploy:www-data /srv/monsiteweb/.env
            chmod 640 /srv/monsiteweb/.env


            echo "== Contenu de .env =="
            cat /srv/monsiteweb/.env
            

            # 3. Exécute le script de déploiement (ex: git pull + migrations)
            cd /srv/monsiteweb
            ./deploy.sh
